### ISSUE TITLE
"Every N seconds" is executed also every minute at second N

### ISSUE THREAD

**Issue by calippo** [philcali/cronish#19]
`Every N seconds` statement is executed:
- Every N seconds
- Every minute at second N

For example, with N = 50

<img width="1172" alt="screen shot 2016-08-30 at 15 02 51" src="https://cloud.githubusercontent.com/assets/2476080/18090332/7f140bfa-6ec4-11e6-8ba2-5a370fd2f697.png">

**Comment by calippo** [comment]
Going deeper into the problem, it looks like the scheduler is resetted every minute.
For instance, with `N = 7`, the task is executed at minute `1:03` (9th execution), at `1:07` and at `1:14` (also `println(cron.nextFrom(now))`) is wrong.

<img width="381" alt="screen shot 2016-08-30 at 15 23 25" src="https://cloud.githubusercontent.com/assets/2476080/18090594/cc55c538-6ec5-11e6-955d-2977a212369e.png">

**Comment by federico-pellegatta** [comment]
I have traced back the issue to the following line: [cron.scala#L98](/philcali/cronish/blob/master/src/main/scala/cron.scala#L98)

If the current field value (say `valr = 3` seconds for `15:18:03`) module the interval (say each `mod = 7` seconds) is not zero (`modder = valr % mod`), then the next value will be computed as (`valr - modder + mod` which is `7` in our example).

**Comment by federico-pellegatta** [comment]
The observed behaviour is an exact replica of what cron does:
> Note that frequencies in general cannot be expressed; only step values which evenly divide their range express accurate frequencies (for minutes and seconds, that's /2, /3, /4, /5, /6, /10, /12, /15, /20 and /30 because 60 is evenly divisible by those numbers; for hours, that's /2, /3, /4, /6, /8 and /12); all other possible "steps" and all other fields yield inconsistent "short" periods at the end of the time-unit before it "resets" to the next minute, second, or day;

**Comment by calippo** [comment]
closing, not a real issue
