### ISSUE TITLE
Task not run when the day has already started

### ISSUE THREAD

**Issue by ex0ns** [philcali/cronish#21]
The title of this issue might not be very explicit, but here is how to reproduce the issue:

```scala
import cronish.Cron
import cronish.dsl._
import scalendar._

object main {

  def main(argv: Array[String]): Unit = {
    def print = println("task called")

    val cron = Cron("00", "*/15", "9-23", "*", "*", "1,3,5", "*")

    task(print) executes cron 
    println(cron.nextTime)
  }

}
```

I would expect the previous code to print `task called` every fifteen minutes between 9AM and 11PM, only on Monday, Wednesday and Friday.

It works, unless I'm running it a Monday, Wednesday of Friday, indeed (the code is ran on Monday November 14th at 1:15PM), I would expect `nextTime` to be 1:30 the same day ! Here is what it prints:

```11/16/2016 13:30:00```

The time is correct but the date is November 16th (next Wednesday), I don't think this is the expected behaviour

If I change the cron to  `Cron("00", "*/15", "9-23", "*", "*", "*", "*")` it prints the correct answer (`11/14/2016 13:30:00`)

**Comment by zifeo** [comment]
I'm facing the same issue. @philcali could you take at look at #23 please?
